title: Ngzhio's Blog
description: The personal blog of Shangzhi Huang
url: https://ngzhio.github.io
author: Shangzhi Huang
avatar: /avatar.jpg
email: ngzhio@gmail.com
location: Shenzhen, China
timezone: +0000
theme: jekyll-theme-minimal
