title: IMBA
url: https://wangyongliang.github.io
author: IMBA
email: wangyongliang.wyl@gmail.com
location: Beijing, China
timezone: +0000
skin: daylight
plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
